# Generated by Django 3.0.8 on 2020-07-12 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='content',
        ),
    ]
